# Generated by Django 5.0.4 on 2024-04-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWavesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
